[2022-01-30 16:50:10] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 16:52:50] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 16:58:00] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 16:58:34] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 16:59:07] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 17:00:15] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 17:02:07] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 17:02:59] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ("'NoneType' object cannot be interpreted as an integer",)
[2022-01-30 17:06:08] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 17:09:42] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 17:16:03] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 17:17:19] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: Den!Отказ. Имя пользователя уже занято.
[2022-01-30 17:18:02] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: Den!Отказ. Имя пользователя уже занято.
[2022-01-30 17:18:33] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 17:19:43] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: Den!Отказ. Имя пользователя уже занято.
[2022-01-30 17:19:55] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 17:24:28] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:31:24] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:32:27] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:44:28] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ('parse_client_msg() takes 5 positional arguments but 6 were given',)
[2022-01-30 18:46:21] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:46:57] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:48:28] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:56:26] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:58:33] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 18:58:41] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:02:42] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:02:44] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 123!Отказ. Имя пользователя уже занято.
[2022-01-30 19:02:53] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:03:32] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:20:09] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:21:47] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:21:56] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:23:13] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:24:20] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: JSONDecodeError, аргументы: ('Expecting value: line 1 column 1 (char 0)',)
[2022-01-30 19:25:30] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:35:15] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: AttributeError, аргументы: ("'list' object has no attribute 'keys'",)
[2022-01-30 19:36:29] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: AttributeError, аргументы: ("'list' object has no attribute 'keys'",)
[2022-01-30 19:37:53] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: TypeError, аргументы: ('list indices must be integers or slices, not str',)
[2022-01-30 19:42:21] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:42:56] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:43:00] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:43:04] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:43:17] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:43:22] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:43:34] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:52:05] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 19:53:30] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 1!Отказ. Имя пользователя уже занято.
[2022-01-30 20:01:04] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:04:08] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:07:16] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 2!Отказ. Имя пользователя уже занято.
[2022-01-30 20:07:33] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:07:59] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:08:27] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:09:16] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:09:40] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:10:26] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:11:12] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:11:28] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:11:36] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:11:41] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:25:08] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:25:39] [ERROR     ] [server  ] [<module>                      ] > Exception: list.remove(x): x not in list
[2022-01-30 20:32:33] [ERROR     ] [server  ] [route_client_msg              ] > Пользователь exit не зарегистрирован на сервере, отправка сообщения невозможна.
[2022-01-30 20:34:18] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:34:23] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:51:28] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:52:57] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:53:03] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:57:22] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 20:58:22] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: Den!Отказ. Имя пользователя уже занято.
[2022-01-30 20:59:27] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 1!Отказ. Имя пользователя уже занято.
[2022-01-30 21:00:54] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 21:02:36] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 21:05:46] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 21:05:51] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 6!Отказ. Имя пользователя уже занято.
[2022-01-30 21:06:24] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 6!Отказ. Имя пользователя уже занято.
[2022-01-30 21:09:09] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 21:09:11] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: 6!Отказ. Имя пользователя уже занято.
[2022-01-30 21:09:47] [ERROR     ] [server  ] [run                           ] > Клиент отключился от сервера. Тип исключения: ValueError, аргументы: ("we don't received any data",)
[2022-01-30 21:16:25] [WARNING   ] [server  ] [parse_client_msg              ] > Повторная попытка авторизации клиента: den!Отказ. Имя пользователя уже занято.
